name: technokhural_flutter_demo
description: Technokhural demo

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.2.0
  http: ^0.13.6
  json_annotation: ^4.8.1

dev_dependencies:
  freezed: ^2.3.3
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  json_serializable: ^6.6.2

flutter:
  uses-material-design: true
